# Generated by Django 2.2 on 2021-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tierlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('likes', models.IntegerField()),
                ('date', models.DateField()),
                ('userId', models.IntegerField()),
                ('gameId', models.IntegerField()),
            ],
        ),
    ]
